services:
  fraud-lens:
    build: .
    env_file:
      - path: .env
        required: false
    volumes:
      - ./src/data:/home/app/fraud-lens/src/data
      - ./reports:/home/app/fraud-lens/reports
